# Generated by Django 3.2.15 on 2024-01-08 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('dt_register', models.DateTimeField(auto_now_add=True)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretaria_financas.setor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_register', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
