# Generated by Django 3.2.15 on 2023-03-31 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log_estoque',
            name='tipo_movimentacao',
            field=models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], default='E', max_length=1),
        ),
        migrations.AlterField(
            model_name='log_estoque',
            name='add_quantidade',
            field=models.IntegerField(verbose_name='Quantidade movimentada'),
        ),
    ]
