# Generated by Django 3.2.15 on 2023-06-16 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamados_dev', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_Tipo_OS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Especificação')),
                ('sigla', models.CharField(blank=True, max_length=10, null=True, verbose_name='Sigla')),
                ('tipo_os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamados_dev.tipo_os')),
            ],
        ),
    ]
