# Generated by Django 3.2.15 on 2023-06-16 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamados_dev', '0002_sub_tipo_os'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devordemdeservico',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='devordemdeservico',
            name='logradouro',
        ),
        migrations.RemoveField(
            model_name='devordemdeservico',
            name='referencia',
        ),
    ]
