# Generated by Django 3.2.15 on 2023-06-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados_dev', '0004_alter_sub_tipo_os_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='devordemdeservico',
            name='secretaria_solicitante',
            field=models.CharField(blank=True, max_length=200, verbose_name='Secretária solicitante'),
        ),
    ]
