# Generated by Django 3.2.15 on 2024-07-31 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.CharField(choices=[('<i class="text-success fa-solid fa-list-check my-auto me-4"></i>', 'Checkin icon'), ('<i class="fa-solid fa-file-invoice-dollar"></i>', 'Payment icon')], max_length=150, verbose_name='Qual icone deve ser exibido?')),
                ('referencia', models.CharField(max_length=40, verbose_name='Qual é a referência? Referência é o texto menor na notificação.')),
                ('mensagem', models.CharField(max_length=36, verbose_name='Qual mensagem deve ser exibida?')),
                ('url_redirect', models.CharField(max_length=150, verbose_name='Qual URL deve ser redirecionada?')),
                ('hash', models.CharField(blank=True, max_length=150, null=True, verbose_name='Hash da notificação')),
                ('viewed', models.BooleanField(default=False, verbose_name='Visualizado?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('for_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que deve ser notificado')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
            },
        ),
    ]
