# Generated by Django 3.2.15 on 2024-07-31 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Reunião',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('dia', models.CharField(choices=[('S', 'Segunda-feira'), ('T', 'Terça-feira'), ('Q', 'Quarta-feira'), ('Q', 'Quinta-feira'), ('S', 'Sexta-feira'), ('S', 'Sábado'), ('D', 'Domingo')], max_length=1, verbose_name='Dia da semana')),
            ],
        ),
        migrations.CreateModel(
            name='Voto_Relator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('arquivo', models.FileField(upload_to='votos/', verbose_name='Arquivo do Voto')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
                ('user_inclusao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sumulas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('numero', models.CharField(max_length=50)),
                ('assunto', models.CharField(max_length=100)),
                ('conteudo', models.TextField(verbose_name='Texto da Súmula')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField()),
                ('user_inclusao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pauta_de_Julgamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representante', models.CharField(max_length=150)),
                ('relator', models.CharField(max_length=150)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('local', models.CharField(max_length=100)),
                ('processos', models.TextField(verbose_name='Processos em pauta (Separe por ponto e vírgula)')),
                ('numero', models.IntegerField()),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField()),
                ('user_inclusao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conselheiros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('ativo', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
                ('user_inclusao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('numero', models.CharField(max_length=50)),
                ('ata', models.FileField(null=True, upload_to='atas/', verbose_name='Arquivo da Ata')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField()),
                ('participantes', models.ManyToManyField(to='financas.Conselheiros')),
                ('reuniao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.pauta_de_julgamento', verbose_name='Reunião')),
                ('user_inclusao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Acordao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('numero', models.CharField(max_length=50, verbose_name='Número do Acórdão')),
                ('processo', models.CharField(max_length=50, verbose_name='Número do processo')),
                ('recorrente', models.CharField(max_length=150)),
                ('recorrido', models.CharField(max_length=150)),
                ('relator', models.CharField(max_length=150)),
                ('ementa', models.TextField(verbose_name='Ementa do Acórdão')),
                ('inteiro', models.FileField(upload_to='acordaos/', verbose_name='Arquivo do Acórdão')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField()),
                ('reuniao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.pauta_de_julgamento')),
                ('user_inclusao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
