# Generated by Django 3.2.15 on 2024-04-05 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0003_auto_20240404_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='acordao',
            name='Relator',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acordao',
            name='processo',
            field=models.CharField(default='', max_length=50, verbose_name='Número do processo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acordao',
            name='recorrido',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acordao',
            name='numero',
            field=models.CharField(max_length=50, verbose_name='Número do Acórdão'),
        ),
        migrations.AlterField(
            model_name='ata',
            name='reuniao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.pauta_de_julgamento', verbose_name='Reunião'),
        ),
    ]
