# Generated by Django 3.2.15 on 2024-04-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0005_auto_20240405_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Reunião',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('dia', models.CharField(choices=[('S', 'Segunda-feira'), ('T', 'Terça-feira'), ('Q', 'Quarta-feira'), ('Q', 'Quinta-feira'), ('S', 'Sexta-feira'), ('S', 'Sábado'), ('D', 'Domingo')], max_length=1, verbose_name='Dia da semana')),
            ],
        ),
    ]
