# Generated by Django 3.2.15 on 2024-04-05 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0006_data_reunião'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acordao',
            old_name='Relator',
            new_name='relator',
        ),
    ]
