# Generated by Django 3.2.15 on 2025-02-12 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financas', '0007_rename_relator_acordao_relator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe_Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('div_id', models.CharField(max_length=10)),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
                ('user_inclusao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Formularios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('arquivo', models.FileField(upload_to='formularios/', verbose_name='Arquivo do Formulário')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.classe_formulario')),
                ('user_inclusao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
