# Generated by Django 3.2.15 on 2025-02-12 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0008_classe_formulario_formularios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe_formulario',
            name='user_inclusao',
        ),
        migrations.RemoveField(
            model_name='formularios',
            name='user_inclusao',
        ),
    ]
