# Generated by Django 3.2.16 on 2022-11-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='grupo_whatsapp',
            field=models.URLField(blank=True, null=True),
        ),
    ]
