# Generated by Django 3.2.15 on 2022-09-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='escolaridade',
            field=models.CharField(choices=[('efi', 'Ensino Fundamental Incompleto'), ('efc', 'Ensino Fundamental Completo'), ('emi', 'Ensino Médio Incompleto'), ('emc', 'Ensino Médio Completo'), ('ct', 'Curso Técnico'), ('esi', 'Ensino Superior Incompleto'), ('esc', 'Ensino Superior Completo')], default='esi', max_length=3, verbose_name='Escolaridade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidato',
            name='estado_civil',
            field=models.CharField(choices=[('s', 'Solteiro'), ('c', 'Casado'), ('s', 'Separado'), ('d', 'Divorciado'), ('v', 'Viúvo')], default='s', max_length=1, verbose_name='Estado Civil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidato',
            name='profissão',
            field=models.CharField(default='', max_length=150, verbose_name='Profissão'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='local',
            name='bairro',
            field=models.CharField(max_length=80, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='celular',
            field=models.CharField(max_length=12, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='endereco',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Nome completo do professor'),
        ),
    ]
