# Generated by Django 3.2.15 on 2022-10-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='nome_da_mãe',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Prefiro não dizer')], max_length=1, verbose_name='Qual foi o sexo atribuído no seu nascimento?'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='r_bairro',
            field=models.CharField(max_length=80, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='r_cpf',
            field=models.CharField(max_length=14, verbose_name='CPF'),
        ),
    ]
