# Generated by Django 3.2.12 on 2022-12-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_turma_grupo_whatsapp'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='turma',
        #     name='instrutor',
        # ),
        # migrations.AddField(
        #     model_name='turma',
        #     name='instrutor',
        #     field=models.ManyToManyField(to='cursos.Instrutor'),
        # ),
    ]
