# Generated by Django 3.2.16 on 2022-12-08 19:29

import cursos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_turma_grupo_whatsapp'),
    ]

    operations = [


        migrations.AlterField(
            model_name='turma',
            name='grupo_whatsapp',
            field=models.URLField(blank=True, null=True, verbose_name='Link do grupo do Whatsapp'),
        )
    ]
