# Generated by Django 3.2.15 on 2022-09-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_matricula_data_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='cand_aluno',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='cand_selecionado',
        ),
        migrations.AddField(
            model_name='candidato',
            name='turmas_selecionado',
            field=models.ManyToManyField(related_name='tselecionado', to='cursos.Turma'),
        ),
    ]
