# Generated by Django 3.2.15 on 2022-09-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_auto_20220909_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='li_e_aceito_termos',
            field=models.BooleanField(default=False, verbose_name='Li e aceito os termos'),
        ),
    ]
