# Generated by Django 3.2.15 on 2022-09-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_candidato_li_e_aceito_termos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='estado_civil',
            field=models.CharField(choices=[('s', 'Solteiro(a)'), ('c', 'Casado(a)'), ('s', 'Separado(a)'), ('d', 'Divorciado(a)'), ('v', 'Viúvo(a)')], max_length=1, verbose_name='Estado Civil'),
        ),
    ]
