# Generated by Django 3.2.16 on 2022-12-13 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_remove_matricula_matricula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='data_matricula',
            new_name='dt_inclusao',
        ),
    ]
