# Generated by Django 3.2.15 on 2022-09-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_auto_20220908_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='qnt',
            field=models.IntegerField(default=20, verbose_name='Quantidade de alunos permitidos'),
            preserve_default=False,
        ),
    ]
