# Generated by Django 3.2.15 on 2022-09-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_candidato_estado_civil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='celular',
            field=models.CharField(max_length=15, verbose_name='Celular p/ contato do candidato'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='rg',
            field=models.CharField(blank=True, max_length=12, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='celular',
            field=models.CharField(max_length=15, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='cpf',
            field=models.CharField(max_length=14, verbose_name='CPF'),
        ),
    ]
