# Generated by Django 3.2.16 on 2022-12-13 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_rename_data_matricula_matricula_dt_inclusao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turma',
            old_name='qnt',
            new_name='quantidade_permitido',
        ),
    ]
