# Generated by Django 3.2.15 on 2022-09-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_auto_20220920_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='celular',
            field=models.CharField(max_length=15, verbose_name='Celular p/ contato do aluno'),
        ),
    ]
