# Generated by Django 3.2.15 on 2022-09-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_turma_qnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='aceita_mais_informacoes',
            field=models.BooleanField(default=True, verbose_name='Aceita receber informações por email?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidato',
            name='cep',
            field=models.CharField(default=0, max_length=9, verbose_name='CEP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidato',
            name='nome_da_mãe',
            field=models.CharField(default='mae', max_length=150, verbose_name='Nome completo do candidato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidato',
            name='rg',
            field=models.CharField(blank=True, max_length=9, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='turmas_selecionado',
            field=models.ManyToManyField(blank=True, null=True, related_name='tselecionado', to='cursos.Turma'),
        ),
    ]
