# Generated by Django 3.2.16 on 2022-12-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_rename_qnt_turma_quantidade_permitido'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='aluno',
        #     name='aceita_mais_informacoes',
        #     field=models.BooleanField(default=1, verbose_name='Declaro que aceito receber email com as informações das atividades'),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='aluno',
        #     name='cep',
        #     field=models.CharField(default=0, max_length=9, verbose_name='CEP'),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='aluno',
        #     name='escolaridade',
        #     field=models.CharField(choices=[('efi', 'Ensino Fundamental Incompleto'), ('efc', 'Ensino Fundamental Completo'), ('emi', 'Ensino Médio Incompleto'), ('emc', 'Ensino Médio Completo'), ('ct', 'Curso Técnico'), ('esi', 'Ensino Superior Incompleto'), ('esc', 'Ensino Superior Completo')], default=1, max_length=3, verbose_name='Escolaridade'),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='aluno',
        #     name='estado_civil',
        #     field=models.CharField(choices=[('s', 'Solteiro(a)'), ('c', 'Casado(a)'), ('s', 'Separado(a)'), ('d', 'Divorciado(a)'), ('v', 'Viúvo(a)')], default=1, max_length=1, verbose_name='Estado Civil'),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='aluno',
        #     name='li_e_aceito_termos',
        #     field=models.BooleanField(default=False, verbose_name='Li e aceito os termos'),
        # ),
        # migrations.AddField(
        #     model_name='aluno',
        #     name='profissão',
        #     field=models.CharField(default=1, max_length=150, verbose_name='Profissão'),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='aluno',
        #     name='rg',
        #     field=models.CharField(blank=True, max_length=12, verbose_name='RG'),
        # ),
        migrations.AlterField(
            model_name='aluno',
            name='celular',
            field=models.CharField(max_length=15, verbose_name='Celular p/ contato do candidato'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(max_length=150, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='dt_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email p/ contato do candidato'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='endereco',
            field=models.CharField(max_length=150, null=True, verbose_name='Endereço do candidato'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Nome completo do candidato'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Prefiro não dizer')], max_length=1, verbose_name='Qual foi o sexo atribuído no seu nascimento?'),
        ),
    ]
