# Generated by Django 3.2.15 on 2022-09-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_alter_aluno_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='idade_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Idade máxima'),
        ),
        migrations.AddField(
            model_name='turma',
            name='idade_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Idade mínima'),
        ),
    ]
