# Generated by Django 3.2.12 on 2023-01-13 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_auto_20221213_0957'),
        ('cursos', '0006_rename_qnt_turma_quantidade_permitido'),
    ]

    operations = [
    ]
