# Generated by Django 3.2.16 on 2022-12-13 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_auto_20221213_0957'),
        ('cursos', '0007_auto_20221213_1450'),
    ]

    operations = [
    ]
