# Generated by Django 3.2.13 on 2022-09-23 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_auto_20220923_1409'),
        ('cursos', '0007_auto_20220920_1628'),
    ]

    operations = [
    ]
