# Generated by Django 3.2.16 on 2022-12-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_merge_0003_auto_20221213_0957_0007_auto_20221213_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='instrutor',
            field=models.ManyToManyField(to='cursos.Instrutor', verbose_name='Instrutor(es)'),
        ),
    ]
