# Generated by Django 3.2.16 on 2022-11-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_merge_0005_auto_20220923_1409_0007_auto_20220920_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(max_length=150, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='turmas_selecionado',
            field=models.ManyToManyField(blank=True, related_name='tselecionado', to='cursos.Turma'),
        ),
    ]
