# Generated by Django 3.2.15 on 2022-09-27 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_auto_20220923_1545'),
        ('cursos', '0009_auto_20220927_1209'),
    ]

    operations = [
    ]
