# Generated by Django 4.1.3 on 2022-12-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_auto_20221215_1429'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='matricula',
        #     old_name='data_matricula',
        #     new_name='dt_inclusao',
        # ),
        # migrations.RenameField(
        #     model_name='turma',
        #     old_name='qnt',
        #     new_name='quantidade_permitido',
        # ),
        migrations.RemoveField(
            model_name='responsavel',
            name='r_rg',
        ),
        migrations.AddField(
            model_name='aluno',
            name='aceita_mais_informacoes',
            field=models.BooleanField(default=1, verbose_name='Declaro que aceito receber email com as informações das atividades'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='cep',
            field=models.CharField(default=1, max_length=9, verbose_name='CEP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='escolaridade',
            field=models.CharField(choices=[('efi', 'Ensino Fundamental Incompleto'), ('efc', 'Ensino Fundamental Completo'), ('emi', 'Ensino Médio Incompleto'), ('emc', 'Ensino Médio Completo'), ('ct', 'Curso Técnico'), ('esi', 'Ensino Superior Incompleto'), ('esc', 'Ensino Superior Completo')], default=1, max_length=3, verbose_name='Escolaridade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='estado_civil',
            field=models.CharField(choices=[('s', 'Solteiro(a)'), ('c', 'Casado(a)'), ('s', 'Separado(a)'), ('d', 'Divorciado(a)'), ('v', 'Viúvo(a)')], default=1, max_length=1, verbose_name='Estado Civil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='li_e_aceito_termos',
            field=models.BooleanField(default=False, verbose_name='Li e aceito os termos'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='profissão',
            field=models.CharField(default=1, max_length=150, verbose_name='Profissão'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='turma',
            name='instrutor',
        ),
        migrations.AddField(
            model_name='turma',
            name='instrutor',
            field=models.ManyToManyField(to='cursos.instrutor', verbose_name='Instrutor(es)'),
        ),
    ]
