# Generated by Django 3.2.15 on 2022-09-27 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_merge_0009_auto_20220923_1545_0009_auto_20220927_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel',
            name='dt_inclusao',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
