# Generated by Django 3.2.15 on 2022-09-27 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_responsavel_dt_inclusao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsavel',
            old_name='r_profissão',
            new_name='r_profissao',
        ),
    ]
