# Generated by Django 3.2.15 on 2024-07-31 14:38

from django.db import migrations, models
import django.db.models.deletion
import processos_empreendedor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sala_do_empreendedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequerimentoISS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autonomo_localizado', models.CharField(choices=[('s', 'Sim'), ('n', 'Não')], max_length=1, verbose_name='Autônomo localizado?')),
                ('n_inscricao', models.CharField(blank=True, max_length=128, null=True, verbose_name='Número de inscrição')),
                ('dt_solicitacao', models.DateField(auto_now_add=True, null=True, verbose_name='Data de solicitação')),
                ('dt_atualizacao', models.DateField(auto_now=True, null=True, verbose_name='Data de atualização')),
                ('processo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sala_do_empreendedor.processo_digital', verbose_name='Processo')),
                ('profissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sala_do_empreendedor.profissao', verbose_name='Profissão')),
            ],
        ),
        migrations.CreateModel(
            name='StatusDocumentosRequerimentoISS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rg_status', models.CharField(choices=[('0', 'Aguardando avaliação'), ('1', 'Aprovado'), ('2', 'Aguardando reenvio!')], default='0', max_length=1, verbose_name='Status do RG')),
                ('comprovante_endereco_status', models.CharField(choices=[('0', 'Aguardando avaliação'), ('1', 'Aprovado'), ('2', 'Aguardando reenvio!')], default='0', max_length=1, verbose_name='Status do comprovante de endereço')),
                ('diploma_ou_certificado_status', models.CharField(choices=[('0', 'Aguardando avaliação'), ('1', 'Aprovado'), ('2', 'Aguardando reenvio!')], default='0', max_length=1, verbose_name='Status do diploma ou certificado')),
                ('espelho_iptu_status', models.CharField(choices=[('0', 'Aguardando avaliação'), ('1', 'Aprovado'), ('2', 'Aguardando reenvio!')], default='0', max_length=1, verbose_name='Status Licenca Sanitária Anterior')),
                ('agente_att_certificado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificado_anexos', to='sala_do_empreendedor.agente_tributario', verbose_name='Agente que autalizou o status do Certificado/Diploma')),
                ('agente_att_endereco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comprovante_endereco_anexos', to='sala_do_empreendedor.agente_tributario', verbose_name='Agente que autalizou o status do comprovante de endereço')),
                ('agente_att_rg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rg_anexos', to='sala_do_empreendedor.agente_tributario', verbose_name='Agente que autalizou o status do RG')),
                ('requerimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processos_empreendedor.requerimentoiss', verbose_name='Requerimento')),
            ],
        ),
        migrations.CreateModel(
            name='StatusDocumentosLicencaSanitaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprovante_ar_condicionado_status', models.CharField(choices=[('0', 'Aguardando avaliação'), ('1', 'Aprovado'), ('2', 'Aguardando reenvio!')], default='0', max_length=1, verbose_name='Status Comprovante Ar Condicionado')),
                ('comprovante_limpeza_caixa_dagua_status', models.CharField(choices=[('0', 'Aguardando avaliação'), ('1', 'Aprovado'), ('2', 'Aguardando reenvio!')], default='0', max_length=1, verbose_name="Status Limpeza Caixa d'Agua")),
                ('plano_gerenciamento_de_residuos_status', models.CharField(choices=[('0', 'Aguardando avaliação'), ('1', 'Aprovado'), ('2', 'Aguardando reenvio!')], default='0', max_length=1, verbose_name='Status Gerenciamento de Resíduos')),
                ('licenca_santinaria_anterior_status', models.CharField(choices=[('0', 'Aguardando avaliação'), ('1', 'Aprovado'), ('2', 'Aguardando reenvio!')], default='0', max_length=1, verbose_name='Status Licenca Sanitária Anterior')),
                ('agente_att_ar_condicionado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agente_ar_anexos', to='sala_do_empreendedor.agente_sanitario', verbose_name='Agente que autalizou o status da manutenção do ar')),
                ('agente_att_caixa_comprovante_limpeza_caixa_dagua', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agente_caixa_dagua_anexos', to='sala_do_empreendedor.agente_sanitario', verbose_name="Agente que autalizou o status da caixa d'água")),
                ('agente_att_licenca_sanitaria_anterior', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agente_licenca_sanitaria_anexos', to='sala_do_empreendedor.agente_sanitario', verbose_name='Agente que autalizou o status da antiga licença sanitária')),
                ('agente_att_plano_gerenciamento_de_residuos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agente_residuos_anexos', to='sala_do_empreendedor.agente_sanitario', verbose_name='Agente que autalizou o status do plano de resíduos')),
                ('requerimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processos_empreendedor.requerimentoiss', verbose_name='Requerimento')),
            ],
        ),
        migrations.CreateModel(
            name='StatusDocumentosLicencaAmbiental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato_locacao_status', models.CharField(choices=[('0', 'Aguardando avaliação'), ('1', 'Aprovado'), ('2', 'Aguardando reenvio!')], default='0', max_length=1, verbose_name='Status do contrato de locação')),
                ('conta_dagua_status', models.CharField(choices=[('0', 'Aguardando avaliação'), ('1', 'Aprovado'), ('2', 'Aguardando reenvio!')], default='0', max_length=1, verbose_name='Status conta dagua')),
                ('conta_luz_status', models.CharField(choices=[('0', 'Aguardando avaliação'), ('1', 'Aprovado'), ('2', 'Aguardando reenvio!')], default='0', max_length=1, verbose_name='Status conta de luz')),
                ('foto_status', models.CharField(choices=[('0', 'Aguardando avaliação'), ('1', 'Aprovado'), ('2', 'Aguardando reenvio!')], default='0', max_length=1, verbose_name='Status da foto')),
                ('croqui_acesso_status', models.CharField(choices=[('0', 'Aguardando avaliação'), ('1', 'Aprovado'), ('2', 'Aguardando reenvio!')], default='0', max_length=1, verbose_name='Status Licenca Sanitária Anterior')),
                ('agente_att_conta_dagua', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agente_conta_dagua_anexos', to='sala_do_empreendedor.agente_sanitario', verbose_name='Agente que autalizou o status da conta dagua')),
                ('agente_att_conta_luz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agente_conta_luz_anexos', to='sala_do_empreendedor.agente_sanitario', verbose_name='Agente que autalizou o status da conta de luz')),
                ('agente_att_contrato_locacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agente_contrato_locacao_anexos', to='sala_do_empreendedor.agente_sanitario', verbose_name='Agente que autalizou o status do contrato de locação')),
                ('agente_att_croqui', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agente_croqui_anexos', to='sala_do_empreendedor.agente_sanitario', verbose_name='Agente que autalizou o status da manutenção do ar')),
                ('agente_att_foto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agente_foto_anexos', to='sala_do_empreendedor.agente_sanitario', verbose_name='Agente que autalizou o status da foto da empresa')),
                ('requerimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processos_empreendedor.requerimentoiss', verbose_name='Requerimento')),
            ],
        ),
        migrations.CreateModel(
            name='Relatorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_register', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de registro')),
                ('descricao', models.TextField(verbose_name='Texto')),
                ('processo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sala_do_empreendedor.processo_digital', verbose_name='Processo')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sala_do_empreendedor.agente_tributario', verbose_name='Agente Tributário')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentosRequerimentoISS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rg', models.FileField(null=True, upload_to='processos/rg_cnh/', verbose_name='RG/CNH/Passaporte')),
                ('comprovante_endereco', models.FileField(null=True, upload_to='processos/comprovante_endereco/', verbose_name='Comprovante de endereço')),
                ('diploma_ou_certificado', models.FileField(blank=True, null=True, upload_to='processos/diploma_ou_certificado/', verbose_name='Diploma ou certificado')),
                ('espelho_iptu', models.FileField(blank=True, null=True, upload_to='processos/espelho_iptu/', verbose_name='Espelho do IPTU')),
                ('requerimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processos_empreendedor.requerimentoiss', verbose_name='Requerimento')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentosLicencaSanitaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licenca_sanitaria', models.FileField(blank=True, null=True, upload_to='processos/licenca_sanitaria/', verbose_name='Licença sanitária')),
                ('comprovante_ar_condicionado', models.FileField(blank=True, null=True, upload_to='processos/licenca_sanitaria/', verbose_name='Comprovante de manutenção de ar condicionado')),
                ('comprovante_limpeza_caixa_dagua', models.FileField(blank=True, null=True, upload_to='processos/licenca_sanitaria/', verbose_name="Laudo de serviço e comprovante de limpeza de caixa d'agua por firma credenciada no INEA")),
                ('plano_gerenciamento_de_residuos', models.FileField(blank=True, null=True, upload_to='processos/licenca_sanitaria/', verbose_name='Plano de ferenciamento de resíduos')),
                ('licenca_santinaria_anterior', models.FileField(blank=True, null=True, upload_to='processos/licenca_sanitaria/', verbose_name='Licença sanitária anterior (para renovação)')),
                ('requerimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processos_empreendedor.requerimentoiss', verbose_name='Requerimento')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentosLicencaAmbiental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licenca_ambiental', models.FileField(blank=True, null=True, upload_to='processos/licenca_ambiental/', verbose_name='Licença ambiental')),
                ('contrato_locacao', models.FileField(blank=True, null=True, upload_to='processos/contrato-locacao/', verbose_name='Cópia do contrato de locação, se houver')),
                ('conta_dagua', models.FileField(blank=True, null=True, upload_to='processos/conta-dagua/', verbose_name="Conta d'água")),
                ('conta_luz', models.FileField(blank=True, null=True, upload_to='processos/conta-luz/', verbose_name='Conta de luz')),
                ('foto', processos_empreendedor.models.LimitedImageField(blank=True, help_text='Limite: 2MB', null=True, upload_to='processos/fotos_empresa/', verbose_name='Foto da empresa para possibilitar a vistoria do técnico (jpg ou png)')),
                ('croqui_acesso', processos_empreendedor.models.LimitedImageField(blank=True, help_text='Limite: 2MB', null=True, upload_to='processos/croqui_acesso/', verbose_name='Croqui de acesso para possibilitar a localização e vistoria da local de atuação. (jpg ou png)')),
                ('requerimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processos_empreendedor.requerimentoiss', verbose_name='Requerimento')),
            ],
        ),
        migrations.CreateModel(
            name='BoletosRequerimentoISS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boleto_requerimento', models.FileField(blank=True, null=True, upload_to='processos/boletos/', verbose_name='Boleto Requerimento')),
                ('boleto_licenca_ambiental', models.FileField(blank=True, null=True, upload_to='processos/boletos/', verbose_name='Boleto Licença Ambiental')),
                ('comprovante_licenca_ambiental', models.FileField(blank=True, null=True, upload_to='processos/boletos/', verbose_name='Comprovante de pagamento da Licença Ambiental')),
                ('status_boleto_ambiental', models.BooleanField(default=False, verbose_name='Boleto Licença Ambiental Pago?')),
                ('boleto_licenca_sanitaria', models.FileField(blank=True, null=True, upload_to='processos/boletos/', verbose_name='Boleto Licença Sanitária')),
                ('comprovante_licenca_sanitaria', models.FileField(blank=True, null=True, upload_to='processos/boletos/', verbose_name='Comprovante de pagamento da Licença Sanitária')),
                ('status_boleto_sanitario', models.BooleanField(default=False, verbose_name='Boleto Licença Sanitária Pago?')),
                ('requerimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processos_empreendedor.requerimentoiss', verbose_name='Requerimento')),
            ],
        ),
    ]
