# Generated by Django 3.2.15 on 2024-07-31 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0002_auto_20240731_1509'),
        ('processos_empreendedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorios',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sala_do_empreendedor.agente', verbose_name='Agente'),
        ),
    ]
