# Generated by Django 3.2.15 on 2024-07-31 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0003_auto_20240731_1520'),
        ('processos_empreendedor', '0002_alter_relatorios_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentesRelatorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprovado', models.BooleanField(default=False, verbose_name='Aprovado?')),
                ('dt_register', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de registro')),
                ('agente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sala_do_empreendedor.agente', verbose_name='Agente')),
                ('relatorio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processos_empreendedor.relatorios', verbose_name='Relatório')),
            ],
            options={
                'verbose_name': 'Agente Relatório',
                'verbose_name_plural': 'Agentes Relatórios',
            },
        ),
    ]
