# Generated by Django 3.2.15 on 2024-07-31 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos_empreendedor', '0003_agentesrelatorios'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorios',
            name='aprovado',
            field=models.BooleanField(default=False, verbose_name='Aprovado?'),
        ),
    ]
