# Generated by Django 3.2.15 on 2024-07-31 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autenticacao', '0001_initial'),
        ('almoxarifado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Bairro')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario_OS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('0', '0 - Agente de atendimento'), ('1', '1 - Suporte de campo'), ('2', '2 - Suporte avançado'), ('3', '3 - Coordenador de serviços públicos')], default='0', max_length=1, null=True, verbose_name='Nível de acesso')),
                ('dt_inclusao', models.DateField(auto_now_add=True, verbose_name='Data de inclusão')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacao.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Logradouro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Logradouro')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemDeServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=130, verbose_name='Nº da OS')),
                ('prioridade', models.CharField(choices=[('0', 'Normal'), ('1', 'Moderada'), ('2', 'Urgente')], default='0', max_length=1, null=True, verbose_name='Prioridade')),
                ('dt_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de solicitação')),
                ('logradouro', models.CharField(max_length=150, verbose_name='Logradouro')),
                ('bairro', models.CharField(max_length=150, verbose_name='Bairro')),
                ('referencia', models.CharField(blank=True, max_length=200, verbose_name='Referência')),
                ('nome_do_contribuinte', models.CharField(blank=True, max_length=200, verbose_name='Nome do contribuinte')),
                ('telefone_do_contribuinte', models.CharField(blank=True, max_length=12, verbose_name='Telefone do contribuinte')),
                ('motivo_reclamacao', models.TextField(verbose_name='Motivo da solicitação')),
                ('status', models.CharField(choices=[('0', 'Novo'), ('1', 'Aguardando'), ('2', 'Em execução'), ('f', 'Finalizado')], default='0', max_length=1, null=True, verbose_name='Status')),
                ('pontos_atendidos', models.PositiveIntegerField(default=0)),
                ('observacao_pontos', models.TextField(blank=True, default='', null=True, verbose_name='Observação')),
                ('dt_alteracao', models.DateTimeField(blank=True, null=True, verbose_name='Data de alteração')),
                ('dt_execucao', models.DateTimeField(blank=True, null=True, verbose_name='Data de execução')),
                ('dt_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de conclusão')),
                ('message_status', models.CharField(choices=[('0', 'Sem mensagens'), ('1', 'Mensagens lidas'), ('2', 'Nova mensagem')], default='0', max_length=1, null=True, verbose_name='Status de mensagens')),
                ('atendente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='autenticacao.pessoa')),
                ('finalizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordem_finalizada_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dt_alteracao', '-dt_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='Tipo_OS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Tipo de OS')),
                ('sigla', models.CharField(blank=True, max_length=10, null=True, verbose_name='Sigla')),
            ],
        ),
        migrations.CreateModel(
            name='TotalOSPorMesAno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('total_os', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TotalOSPorSemanaAno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('semana', models.IntegerField()),
                ('total_os', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OS_Linha_Tempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('anexo', models.FileField(blank=True, null=True, upload_to='anexos/')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Data da mensagem')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iluminacao.ordemdeservico')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacao.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='OS_ext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_veiculo', models.CharField(blank=True, max_length=14, verbose_name='Código do veículo')),
                ('equipe', models.ManyToManyField(blank=True, null=True, to='iluminacao.Funcionario_OS')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iluminacao.ordemdeservico')),
            ],
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='iluminacao.tipo_os'),
        ),
        migrations.CreateModel(
            name='MateriaisUsados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almoxarifado.material')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iluminacao.ordemdeservico')),
            ],
        ),
        migrations.AddField(
            model_name='funcionario_os',
            name='tipo_os',
            field=models.ManyToManyField(to='iluminacao.Tipo_OS'),
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(blank=True, max_length=200, verbose_name='Referência')),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iluminacao.bairro', verbose_name='Bairro')),
                ('logradouro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iluminacao.logradouro', verbose_name='Logradouro')),
            ],
        ),
    ]
