# Generated by Django 4.2.2 on 2023-08-15 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.CharField(max_length=64, verbose_name='Atividade')),
                ('dt_register', models.DateField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('user_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que cadastrou')),
            ],
        ),
        migrations.CreateModel(
            name='Ramo_de_Atuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ramo', models.CharField(max_length=64, verbose_name='Ramo de atuação')),
                ('dt_register', models.DateField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('user_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que cadastrou')),
            ],
        ),
        migrations.CreateModel(
            name='Porte_da_Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porte', models.CharField(max_length=32, verbose_name='Porte da empresa')),
                ('dt_register', models.DateField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('user_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que cadastrou')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('nome_da_empresa', models.CharField(max_length=128, verbose_name='Nome da empresa')),
                ('outro_ramo', models.CharField(blank=True, max_length=64, null=True, verbose_name='Outro ramo')),
                ('receber_noticias', models.BooleanField(default=False, verbose_name='Deseja receber notificações sobre compras da prefeitura?')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição da empresa')),
                ('dt_register', models.DateField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('atividade', models.ManyToManyField(to='sala_do_empreendedor.atividade', verbose_name='Atividade')),
                ('porte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sala_do_empreendedor.porte_da_empresa', verbose_name='Porte da empresa')),
                ('ramo', models.ManyToManyField(to='sala_do_empreendedor.ramo_de_atuacao', verbose_name='Ramo de atuação')),
                ('user_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que cadastrou')),
            ],
        ),
    ]
