# Generated by Django 4.2.2 on 2023-08-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='nome_da_empresa',
            new_name='nome',
        ),
        migrations.AddField(
            model_name='empresa',
            name='validacao',
            field=models.BooleanField(default=False, verbose_name='Validação da empresa'),
        ),
    ]
