# Generated by Django 3.2.15 on 2024-07-31 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sala_do_empreendedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andamento_processo_digital',
            name='status',
            field=models.CharField(choices=[('nv', 'Novo'), ('ae', 'Aguardando envio de documentos'), ('ar', 'Aguardando reenvio de documentos'), ('aa', 'Aguardando avaliação'), ('bs', 'Aguardando pagamento licença sanitária'), ('ba', 'Aguardando pagamento licença ambiental'), ('sa', 'Aguardando pagamento licença ambiental e licença ambiental'), ('ls', 'Aguardando emissão licença sanitária'), ('la', 'Aguardando emissão licença ambiental'), ('se', 'Licença ambiental sanitária'), ('am', 'Licença ambiental emitida'), ('bg', 'Boleto gerado'), ('cn', 'Concluído')], default='nv', max_length=2, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email para receber notificação de processo')),
                ('ativo', models.BooleanField(default=True)),
                ('dt_register', models.DateField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Agente Ambiental')),
            ],
        ),
    ]
