# Generated by Django 3.2.15 on 2024-07-31 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
        ('sala_do_empreendedor', '0002_auto_20240731_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agente',
            name='user',
        ),
        migrations.AddField(
            model_name='agente',
            name='pessoa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='autenticacao.pessoa', verbose_name='Pessoa'),
        ),
    ]
