# Generated by Django 4.2.2 on 2023-08-16 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0002_rename_nome_da_empresa_empresa_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='fornecedor',
            field=models.BooleanField(default=False, verbose_name='Cadastrado como fornecedor da prefeitura?'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='vitrine',
            field=models.BooleanField(default=False, verbose_name='Cadastrado na Vitrine Virtual?'),
        ),
    ]
