# Generated by Django 4.2.2 on 2023-08-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0004_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail da empresa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Telefone de contato'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Whatsapp da empresa'),
        ),
    ]
