# Generated by Django 4.2.2 on 2023-08-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0005_empresa_email_empresa_telefone_empresa_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone de contato'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Whatsapp da empresa'),
        ),
        migrations.DeleteModel(
            name='Fornecedor',
        ),
    ]
