# Generated by Django 4.2.2 on 2023-08-16 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0006_alter_empresa_telefone_alter_empresa_whatsapp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='registro_no_vitrine_virtual',
            name='produtos',
        ),
        migrations.AddField(
            model_name='produto',
            name='rg_vitrine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sala_do_empreendedor.registro_no_vitrine_virtual', verbose_name='Registro da vitrine virtual'),
            preserve_default=False,
        ),
    ]
