# Generated by Django 4.2.2 on 2023-08-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0007_remove_produto_empresa_remove_produto_preco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_no_vitrine_virtual',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo da empresa'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=128, verbose_name='Nome do produto ou serviço'),
        ),
    ]
