# Generated by Django 4.2.2 on 2023-08-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0008_registro_no_vitrine_virtual_logo_alter_produto_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='validacao_da_equipe',
            field=models.BooleanField(default=False, verbose_name='Validação da Sala do Empreendedor'),
        ),
    ]
