# Generated by Django 4.2.2 on 2023-08-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0009_produto_validacao_da_equipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramo_de_atuacao',
            name='ramo',
            field=models.CharField(max_length=164, verbose_name='Ramo de atuação'),
        ),
    ]
