# Generated by Django 4.2.2 on 2023-08-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0010_alter_ramo_de_atuacao_ramo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='outra_atividade',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Outra atividade'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='atividade',
            field=models.ManyToManyField(to='sala_do_empreendedor.atividade', verbose_name='Atividade (Segure CTRL para selecionar mais de uma)'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ramo',
            field=models.ManyToManyField(to='sala_do_empreendedor.ramo_de_atuacao', verbose_name='Ramo de atuação (Segure CTRL para selecionar mais de um)'),
        ),
    ]
