# Generated by Django 4.2.2 on 2023-09-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0011_empresa_outra_atividade_alter_empresa_atividade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='site',
            field=models.URLField(blank=True, null=True, verbose_name='Site da empresa'),
        ),
    ]
