# Generated by Django 4.2.2 on 2023-09-14 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0012_empresa_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamentos_Faccao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome do equipamento')),
            ],
        ),
        migrations.CreateModel(
            name='tipo_produto_faccao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome do produto')),
            ],
        ),
        migrations.CreateModel(
            name='Trabalho_Faccao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome do trabalho')),
            ],
        ),
        migrations.CreateModel(
            name='faccao_legal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possui_mei', models.BooleanField(default=False, verbose_name='Possui MEI?')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ')),
                ('tempo_que_trabalha', models.CharField(choices=[('0', 'Menos de 1 ano'), ('1', 'De 1 a 3 anos'), ('2', 'Mais de 3 anos')], max_length=1, verbose_name='Trabalha com facção há quanto tempo')),
                ('area', models.CharField(choices=[('s', 'Sim'), ('n', 'Não')], max_length=1, verbose_name='Possui área de trabalho separada da residência?')),
                ('tamanho_area', models.CharField(choices=[('0', 'Menos de 6m²'), ('1', 'De 6 a 16m²'), ('2', 'De 16 a 50m²'), ('3', 'Mais de 50m²')], max_length=1, verbose_name='Qual o tamanho da área de trabalho?')),
                ('possui_colaboradores', models.BooleanField(default=False, verbose_name='Possui colaboradores?')),
                ('qtd_colaboradores', models.IntegerField(blank=True, null=True, verbose_name='Quantos colaboradores possui?')),
                ('outro_produto', models.CharField(blank=True, max_length=128, null=True, verbose_name='Outro produto, descreva')),
                ('situacao_trabalho', models.CharField(choices=[('p', 'Pouco'), ('s', 'Suficiente'), ('d', 'Em demasia')], max_length=1, verbose_name='Geralmente, como está de trabalho?')),
                ('situacao_remuneracao', models.CharField(choices=[('bx', 'Baixa'), ('rg', 'Regular'), ('bo', 'Boa'), ('ot', 'Ótima')], max_length=2, verbose_name='Como está a remuneração?')),
                ('qual_seu_sonho_no_setor', models.TextField(blank=True, null=True, verbose_name='Qual seu sonho no setor?')),
                ('equipamentos', models.ManyToManyField(to='sala_do_empreendedor.equipamentos_faccao', verbose_name='Quais equipamentos possui?')),
                ('tipo_produto', models.ManyToManyField(to='sala_do_empreendedor.tipo_produto_faccao', verbose_name='Que tipos de produtos produz?')),
                ('trabalha_com', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sala_do_empreendedor.trabalho_faccao', verbose_name='Trabalha com')),
            ],
        ),
    ]
