# Generated by Django 4.2.2 on 2023-09-18 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sala_do_empreendedor', '0013_equipamentos_faccao_tipo_produto_faccao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faccao_legal',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='atividade',
            field=models.ManyToManyField(to='sala_do_empreendedor.atividade', verbose_name='Atividade'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ramo',
            field=models.ManyToManyField(to='sala_do_empreendedor.ramo_de_atuacao', verbose_name='Ramo de atuação'),
        ),
        migrations.AlterField(
            model_name='faccao_legal',
            name='possui_mei',
            field=models.BooleanField(default=False, verbose_name='Possui MEI ou empresa de outro porte?'),
        ),
    ]
