# Generated by Django 4.2.2 on 2023-09-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0014_faccao_legal_user_alter_empresa_atividade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faccao_legal',
            name='trabalha_com',
        ),
        migrations.AddField(
            model_name='faccao_legal',
            name='trabalha_com',
            field=models.ManyToManyField(null=True, to='sala_do_empreendedor.trabalho_faccao', verbose_name='Trabalha com'),
        ),
    ]
