# Generated by Django 4.2.2 on 2023-09-25 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0016_alter_faccao_legal_outro_produto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escolaridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome da escolaridade')),
            ],
        ),
        migrations.CreateModel(
            name='Profissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome da profissão')),
                ('licenca_sanitaria', models.BooleanField(default=False, verbose_name='Necessita licença sanitária?')),
                ('escolaridade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sala_do_empreendedor.escolaridade', verbose_name='Escolaridade')),
            ],
        ),
        migrations.CreateModel(
            name='Processo_Digital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_processo', models.CharField(choices=[('0', 'Requerimento de ISS')], max_length=1, verbose_name='Tipo de processo')),
                ('n_protocolo', models.CharField(blank=True, max_length=128, null=True, verbose_name='Número do protocolo')),
                ('rg', models.ImageField(upload_to='processos/rg_cnh/', verbose_name='RG/CNH/Passaporte')),
                ('comprovante_endereco', models.ImageField(upload_to='processos/comprovante_endereco/', verbose_name='Comprovante de endereço')),
                ('diploma_ou_certificado', models.ImageField(blank=True, null=True, upload_to='processos/diploma_ou_certificado/', verbose_name='Diploma ou certificado')),
                ('autonomo_localizado', models.CharField(choices=[('s', 'Sim'), ('n', 'Não')], max_length=1, verbose_name='Autônomo localizado?')),
                ('espelho_iptu', models.ImageField(blank=True, null=True, upload_to='processos/espelho_iptu/', verbose_name='Espelho do IPTU')),
                ('profissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sala_do_empreendedor.profissao', verbose_name='Profissão')),
            ],
        ),
    ]
