# Generated by Django 4.2.2 on 2023-09-25 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0017_escolaridade_profissao_processo_digital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status_do_processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='Status')),
            ],
        ),
        migrations.AddField(
            model_name='processo_digital',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sala_do_empreendedor.status_do_processo', verbose_name='Status'),
            preserve_default=False,
        ),
    ]
