# Generated by Django 4.2.2 on 2023-09-25 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sala_do_empreendedor', '0018_status_do_processo_processo_digital_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo_digital',
            name='status',
        ),
        migrations.AddField(
            model_name='processo_digital',
            name='dt_solicitacao',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Data de solicitação'),
        ),
        migrations.AddField(
            model_name='processo_digital',
            name='solicitante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.CreateModel(
            name='Andamento_Processo_Digital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rg_status', models.BooleanField(default=False, verbose_name='RG/CNH/Passaporte ok?')),
                ('comprovante_endereco_status', models.BooleanField(default=False, verbose_name='Comprovante de endereço ok?')),
                ('observacao', models.TextField(verbose_name='Observação')),
                ('dt_andamento', models.DateField(auto_now=True, verbose_name='Data de atualização')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sala_do_empreendedor.processo_digital', verbose_name='Processo')),
                ('servidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Servidor')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sala_do_empreendedor.status_do_processo', verbose_name='Status')),
            ],
        ),
    ]
