# Generated by Django 4.2.2 on 2023-09-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0019_remove_processo_digital_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='andamento_processo_digital',
            name='comprovante_endereco_status',
        ),
        migrations.AlterField(
            model_name='andamento_processo_digital',
            name='rg_status',
            field=models.CharField(choices=[('0', 'Aguardando avaliação'), ('1', 'Aprovado'), ('2', 'Reprovado')], default='0', max_length=1, verbose_name='Status do RG'),
        ),
    ]
