# Generated by Django 4.2.2 on 2023-09-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0020_remove_andamento_processo_digital_comprovante_endereco_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='andamento_processo_digital',
            name='comprovante_endereco_status',
            field=models.CharField(choices=[('0', 'Aguardando avaliação'), ('1', 'Aprovado'), ('2', 'Reprovado')], default='0', max_length=1, verbose_name='Status do comprovante de endereço'),
        ),
    ]
