# Generated by Django 4.2.2 on 2023-09-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0021_andamento_processo_digital_comprovante_endereco_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo_digital',
            name='licenca_sanitaria',
            field=models.FileField(blank=True, null=True, upload_to='processos/licenca_sanitaria/', verbose_name='Licença sanitária'),
        ),
        migrations.AlterField(
            model_name='processo_digital',
            name='comprovante_endereco',
            field=models.FileField(upload_to='processos/comprovante_endereco/', verbose_name='Comprovante de endereço'),
        ),
        migrations.AlterField(
            model_name='processo_digital',
            name='diploma_ou_certificado',
            field=models.FileField(blank=True, null=True, upload_to='processos/diploma_ou_certificado/', verbose_name='Diploma ou certificado'),
        ),
        migrations.AlterField(
            model_name='processo_digital',
            name='rg',
            field=models.FileField(upload_to='processos/rg_cnh/', verbose_name='RG/CNH/Passaporte'),
        ),
    ]
