# Generated by Django 4.2.2 on 2023-09-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0023_processo_digital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='andamento_processo_digital',
            name='diploma_ou_certificado_status',
            field=models.CharField(choices=[('0', 'Aguardando avaliação'), ('1', 'Aprovado'), ('2', 'Reprovado')], default='0', max_length=1, verbose_name='Status do diploma ou certificado'),
        ),
        migrations.AddField(
            model_name='andamento_processo_digital',
            name='espelho_iptu_status',
            field=models.CharField(choices=[('0', 'Aguardando avaliação'), ('1', 'Aprovado'), ('2', 'Reprovado')], default='0', max_length=1, verbose_name='Status do espelho do IPTU'),
        ),
        migrations.AddField(
            model_name='andamento_processo_digital',
            name='licenca_sanitaria',
            field=models.CharField(choices=[('0', 'Aguardando avaliação'), ('1', 'Aprovado'), ('2', 'Reprovado')], default='0', max_length=1, verbose_name='Status da licença sanitária'),
        ),
        migrations.AlterField(
            model_name='andamento_processo_digital',
            name='observacao',
            field=models.TextField(verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='processo_digital',
            name='status',
            field=models.CharField(choices=[('n', 'Novo'), ('e', 'Em andamento'), ('a', 'Aprovado'), ('r', 'Reprovado')], default='n', max_length=1, verbose_name='Status'),
        ),
    ]
