# Generated by Django 4.2.2 on 2023-09-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0025_remove_andamento_processo_digital_comprovante_endereco_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo_digital',
            name='dt_atualizacao',
            field=models.DateField(auto_now=True, null=True, verbose_name='Data de atualização'),
        ),
    ]
