# Generated by Django 4.2.2 on 2023-10-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0026_processo_digital_dt_atualizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo_digital',
            name='boleto',
            field=models.FileField(blank=True, null=True, upload_to='processos/boleto/', verbose_name='Boleto'),
        ),
        migrations.AlterField(
            model_name='andamento_processo_digital',
            name='observacao',
            field=models.TextField(default='n/h', verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='processo_digital',
            name='status',
            field=models.CharField(choices=[('n', 'Novo'), ('e', 'Em andamento'), ('a', 'Aprovado'), ('r', 'Reprovado'), ('b', 'Boleto gerado')], default='n', max_length=1, verbose_name='Status'),
        ),
    ]
