# Generated by Django 4.2.2 on 2023-10-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0027_processo_digital_boleto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo_digital',
            name='boleto_pago',
            field=models.BooleanField(default=False, verbose_name='Boleto pago?'),
        ),
    ]
