# Generated by Django 4.2.2 on 2023-10-16 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sala_do_empreendedor', '0029_alter_andamento_processo_digital_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andamento_processo_digital',
            name='status',
            field=models.CharField(choices=[('nv', 'Novo'), ('ar', 'Aguardando reenvio de RG'), ('aa', 'Aguardando avaliação'), ('bg', 'Boleto gerado'), ('cn', 'Concluído')], default='n', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='processo_digital',
            name='status',
            field=models.CharField(choices=[('nv', 'Novo'), ('ar', 'Aguardando reenvio de RG'), ('aa', 'Aguardando avaliação'), ('bg', 'Boleto gerado'), ('cn', 'Concluído')], default='n', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='processo_digital',
            name='tipo_processo',
            field=models.CharField(choices=[('0', 'Requerimento de ISS'), ('1', 'Cancelamento de ISS')], max_length=1, verbose_name='Tipo de processo'),
        ),
        migrations.CreateModel(
            name='Processos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome do processo')),
                ('descricao', models.TextField(verbose_name='Descrição do processo')),
                ('dt_register', models.DateField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('user_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que cadastrou')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_register', models.DateField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoa_adm', to=settings.AUTH_USER_MODEL, verbose_name='Pessoa')),
                ('processos_autorizados', models.ManyToManyField(to='sala_do_empreendedor.processos', verbose_name='Processos autorizados')),
                ('user_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_register_adm', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que cadastrou')),
            ],
        ),
    ]
