# Generated by Django 4.2.2 on 2023-10-16 18:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sala_do_empreendedor', '0030_alter_andamento_processo_digital_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Processos',
            new_name='Tipo_Processos',
        ),
    ]
