# Generated by Django 4.2.2 on 2023-10-16 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0031_rename_processos_tipo_processos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo_digital',
            name='tipo_processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sala_do_empreendedor.tipo_processos', verbose_name='Tipo de processo'),
        ),
    ]
