# Generated by Django 3.2.15 on 2024-07-31 14:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do curso')),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=50, verbose_name='Sua matricula')),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='estagio.curso', verbose_name='Seu curso')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aluno_pessoa', to='autenticacao.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Estudante_Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sua matricula')),
                ('status', models.CharField(choices=[('0', 'Candidato'), ('1', 'Estagiando'), ('2', 'Estágio concluído'), ('3', 'Candidatura cancelada')], default=0, max_length=1, verbose_name='Status')),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data inicio')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data termino')),
                ('TCE', models.FileField(blank=True, null=True, upload_to='TCE', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Termo de Compromisso de Estágio')),
                ('estudante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='estagio.estudante')),
            ],
        ),
        migrations.CreateModel(
            name='Locais_de_Estagio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=100, verbose_name='Nome do local')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('telefone_responsavel', models.CharField(max_length=15, null=True, verbose_name='Telefone do responsável do local')),
                ('telefone_local', models.CharField(max_length=15, null=True, verbose_name='Telefone do local')),
                ('quantidade_maxima', models.IntegerField()),
                ('cursos', models.ManyToManyField(to='estagio.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da secretaria')),
                ('telefone', models.CharField(max_length=15, null=True, verbose_name='Telefone da secretaria')),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Universidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da instituição')),
                ('nome_responsavel', models.CharField(max_length=150, verbose_name='Nome do responsável de estágio da instituição')),
                ('contato', models.CharField(max_length=50, verbose_name='Contato do responsável de estágio da instituição')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='estagio/media/logo_universidade/')),
                ('dt_inicio_do_termo', models.DateField(blank=True, null=True)),
                ('dt_vencimento_do_termo', models.DateField(blank=True, null=True)),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vagas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome vagas')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('quantidade_de_vagas', models.IntegerField(verbose_name='Quantidade de vagas')),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(null=True, upload_to='estagio/media/banner_vagas/')),
                ('img2', models.ImageField(null=True, upload_to='estagio/media/banner_vagas/')),
                ('quantidade_maxima', models.IntegerField(blank=True, null=True)),
                ('curso', models.ManyToManyField(to='estagio.Curso')),
                ('locais', models.ManyToManyField(to='estagio.Locais_de_Estagio')),
                ('secretaria', models.ManyToManyField(to='estagio.Secretaria')),
            ],
        ),
        migrations.CreateModel(
            name='Vaga_Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autenticacao.pessoa')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estagio.vagas')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome supervisor')),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('n_vagas', models.IntegerField(verbose_name='Número de vagas')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('celular', models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular')),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autenticacao.pessoa')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estagio.secretaria')),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel_Universidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(default='Cargo do Responsável', max_length=20)),
                ('email_institucional', models.EmailField(max_length=254)),
                ('telefone_institucional', models.CharField(max_length=15, null=True, verbose_name='Telefone')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacao.pessoa')),
                ('universidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estagio.universidade')),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_processo', models.CharField(max_length=8, null=True, verbose_name='Número do processo')),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('estudante_vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estagio.estudante_vaga')),
            ],
        ),
        migrations.AddField(
            model_name='locais_de_estagio',
            name='secretaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estagio.secretaria'),
        ),
        migrations.CreateModel(
            name='Historico_Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'Aguardando liberação de vaga'), ('1', 'Lista de espera'), ('2', 'Aguardando reenvio do TCE'), ('3', 'Aguardando termo assinado pelas partes'), ('4', 'Processo de seleção concluída'), ('5', 'Estágio concluído'), ('6', 'Candidatura cancelada')], default=0, max_length=1, verbose_name='Status')),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('mensagem', models.TextField(blank=True)),
                ('processo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estagio.processo')),
            ],
        ),
        migrations.AddField(
            model_name='estudante_vaga',
            name='local_do_estagio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='estagio.locais_de_estagio'),
        ),
        migrations.AddField(
            model_name='estudante_vaga',
            name='local_do_estagio_de_pretensao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pretensao', to='estagio.locais_de_estagio'),
        ),
        migrations.AddField(
            model_name='estudante_vaga',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='estagio.supervisor'),
        ),
        migrations.AddField(
            model_name='estudante_vaga',
            name='universidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='estagio.universidade'),
        ),
        migrations.AddField(
            model_name='estudante',
            name='universidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='estagio.universidade', verbose_name='Sua universidade atual'),
        ),
        migrations.AddField(
            model_name='curso',
            name='universidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estagio.universidade'),
        ),
    ]
