# Generated by Django 3.2.15 on 2023-05-19 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='nome_curso')),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome_secretaria')),
                ('local', models.CharField(max_length=200, verbose_name='local_secretaria')),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Universidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='nome_universidade')),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vagas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='nome_vagas')),
                ('quantidade_de_vagas', models.IntegerField(verbose_name='quantidade_de_vagas')),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('vagas_id_curso', models.ManyToManyField(to='estagio.Curso')),
                ('vagas_id_secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estagio.secretaria')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome_supervisor')),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('supervisor_id_secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estagio.secretaria')),
                ('supervisor_id_vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estagio.vagas')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='curso_id_universidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='estagio.universidade'),
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome_aluno')),
                ('contato', models.IntegerField(verbose_name='contato_aluno')),
                ('matricula', models.IntegerField(verbose_name='matricula')),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('data_incio', models.DateField(blank=True, null=True, verbose_name='data_inicio')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='data_termino')),
                ('aluno_id_curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='estagio.curso')),
                ('aluno_id_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='estagio.supervisor')),
            ],
        ),
    ]
