# Generated by Django 3.2.15 on 2023-05-12 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estagio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='aluno_id_secretaria',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='aluno_id_universidade',
        ),
    ]
