# Generated by Django 3.2.15 on 2023-05-19 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estagio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='curso_id_universidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estagio.universidade'),
        ),
    ]
