# Generated by Django 3.2.15 on 2023-05-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagio', '0002_alter_curso_curso_id_universidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='status',
            field=models.CharField(choices=[('0', 'Candidato'), ('1', 'Estágiario')], default=0, max_length=1, verbose_name='Status'),
        ),
    ]
