# Generated by Django 3.2.15 on 2023-05-18 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estagio', '0002_auto_20230512_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vagas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='nome_vagas')),
                ('quantidade_de_vagas', models.IntegerField(verbose_name='quantidade_de_vagas')),
                ('vagas_id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='estagio.aluno')),
                ('vagas_id_secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estagio.secretaria')),
                ('vagas_id_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estagio.supervisor')),
            ],
        ),
    ]
