# Generated by Django 3.2.15 on 2023-05-23 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
        ('estagio', '0003_aluno_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='pessoa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='aluno_pessoa', to='autenticacao.pessoa'),
            preserve_default=False,
        ),
    ]
