# Generated by Django 3.2.15 on 2023-05-23 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estagio', '0004_aluno_pessoa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='aluno_id_curso',
            new_name='curso',
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='aluno_id_supervisor',
            new_name='supervisor',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='curso_id_universidade',
            new_name='universidade',
        ),
        migrations.RenameField(
            model_name='supervisor',
            old_name='supervisor_id_secretaria',
            new_name='secretaria',
        ),
        migrations.RenameField(
            model_name='supervisor',
            old_name='supervisor_id_vaga',
            new_name='vaga',
        ),
        migrations.RenameField(
            model_name='vagas',
            old_name='vagas_id_curso',
            new_name='curso',
        ),
        migrations.RenameField(
            model_name='vagas',
            old_name='vagas_id_secretaria',
            new_name='secretaria',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='contato',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='nome',
        ),
    ]
