# Generated by Django 3.2.15 on 2023-05-23 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
        ('estagio', '0005_auto_20230523_1710'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aluno',
            new_name='Estudante',
        ),
    ]
