# Generated by Django 3.2.15 on 2023-05-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagio', '0006_rename_aluno_estudante'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagas',
            name='imagem',
            field=models.ImageField(null=True, upload_to='estagio/media/banner_vagas/'),
        ),
    ]
