# Generated by Django 3.2.15 on 2023-05-25 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estagio', '0007_vagas_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vagas',
            old_name='imagem',
            new_name='img',
        ),
    ]
