# Generated by Django 3.2.15 on 2023-05-25 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estagio', '0008_rename_imagem_vagas_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudante',
            old_name='data_incio',
            new_name='data_inicio',
        ),
    ]
