# Generated by Django 3.2.15 on 2023-05-25 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estagio', '0009_rename_data_incio_estudante_data_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudante',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='estudante',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='estudante',
            name='status',
        ),
        migrations.RemoveField(
            model_name='estudante',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='estudante',
            name='universidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='estagio.universidade'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Estudante_Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'Candidato'), ('1', 'Estágiario')], default=0, max_length=1, verbose_name='Status')),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='data_termino')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='data_inicio')),
                ('estudante', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='estagio.estudante')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='estagio.supervisor')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='estagio.vagas')),
            ],
        ),
    ]
