# Generated by Django 3.2.15 on 2023-05-25 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estagio', '0010_auto_20230525_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante_vaga',
            name='estudante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='estagio.estudante'),
        ),
    ]
