# Generated by Django 3.2.15 on 2023-05-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagio', '0011_alter_estudante_vaga_estudante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante_vaga',
            name='status',
            field=models.CharField(choices=[('0', 'Candidato'), ('1', 'Estágiario'), ('2', 'Concluido')], default=0, max_length=1, verbose_name='Status'),
        ),
    ]
