# Generated by Django 3.2.15 on 2023-06-02 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estagio', '0014_auto_20230602_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretaria',
            name='local',
        ),
        migrations.AddField(
            model_name='vagas',
            name='quantidade_maxima',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'Aguardando documentação do aluno'), ('1', 'Aguardando liberação de vaga'), ('2', 'Aguardando termo assinado pela universidade')], default=0, max_length=1, verbose_name='Status')),
                ('estudante_vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estagio.estudante_vaga')),
            ],
        ),
        migrations.CreateModel(
            name='Locais_de_Estagio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=100, verbose_name='Nome secretaria')),
                ('quantidade_maxima', models.IntegerField()),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estagio.secretaria')),
            ],
        ),
        migrations.CreateModel(
            name='Historico_Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estagio.processo')),
            ],
        ),
        migrations.AddField(
            model_name='estudante_vaga',
            name='local_do_estagio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='estagio.locais_de_estagio'),
        ),
        migrations.AddField(
            model_name='vagas',
            name='locais',
            field=models.ManyToManyField(to='estagio.Locais_de_Estagio'),
        ),
    ]
