# Generated by Django 3.2.15 on 2023-06-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagio', '0016_auto_20230605_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='n_processo',
            field=models.CharField(max_length=8, null=True, verbose_name='Número do processo'),
        ),
    ]
