# Generated by Django 3.2.15 on 2023-06-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagio', '0017_processo_n_processo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='status',
        ),
        migrations.AlterField(
            model_name='historico_processo',
            name='status',
            field=models.CharField(choices=[('0', 'Aguardando documentação do aluno'), ('1', 'Aguardando liberação da univerdade'), ('2', 'Aguardando liberação de vaga'), ('3', 'Aguardando termo assinado pela universidade'), ('4', 'Processo de seleção concluída'), ('5', 'Estágio concluído')], default=0, max_length=1, verbose_name='Status'),
        ),
    ]
