# Generated by Django 3.2.15 on 2023-06-23 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
        ('estagio', '0018_auto_20230605_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsavel_Universidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(default='Responsável', max_length=20)),
                ('email_institucional', models.EmailField(max_length=254)),
                ('telefone_institucional', models.CharField(max_length=15, null=True, verbose_name='Telefone')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacao.pessoa')),
                ('universidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estagio.universidade')),
            ],
        ),
    ]
