# Generated by Django 3.2.15 on 2023-06-26 20:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estagio', '0021_processo_mensagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='mensagem',
        ),
        migrations.AddField(
            model_name='historico_processo',
            name='data_inclusao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudante_vaga',
            name='status',
            field=models.CharField(choices=[('0', 'Candidato'), ('1', 'Estagiando'), ('2', 'Estágio concluído')], default=0, max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historico_processo',
            name='processo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estagio.processo'),
        ),
    ]
