# Generated by Django 3.2.15 on 2023-06-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagio', '0022_auto_20230626_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico_processo',
            name='mensagem',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vagas',
            name='nome',
            field=models.TextField(blank=True, null=True),
        ),
    ]
