# Generated by Django 3.2.15 on 2023-06-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagio', '0024_auto_20230626_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagas',
            name='img2',
            field=models.ImageField(null=True, upload_to='estagio/media/banner_vagas/'),
        ),
    ]
