# Generated by Django 4.2.2 on 2023-08-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagio', '0025_vagas_img2'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudante_vaga',
            name='TCE',
            field=models.FileField(blank=True, null=True, upload_to='TCE', verbose_name='Termo de Compromisso de Estágio'),
        ),
    ]
