# Generated by Django 4.2.2 on 2023-08-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagio', '0028_universidade_ativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universidade',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='estagio/media/logo_universidade/'),
        ),
    ]
