# Generated by Django 4.2.2 on 2023-08-21 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estagio', '0030_remove_locais_de_estagio_cursos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='n_vagas',
            field=models.IntegerField(default=1, verbose_name='Número de vagas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudante',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='estagio.curso', verbose_name='Seu curso'),
        ),
        migrations.AlterField(
            model_name='estudante',
            name='matricula',
            field=models.CharField(max_length=50, verbose_name='Sua matricula'),
        ),
        migrations.AlterField(
            model_name='estudante',
            name='universidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='estagio.universidade', verbose_name='Sua universidade'),
        ),
        migrations.AlterField(
            model_name='estudante_vaga',
            name='matricula',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sua matricula'),
        ),
    ]
