# Generated by Django 4.2.2 on 2023-09-04 20:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagio', '0031_supervisor_celular_supervisor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locais_de_estagio',
            name='cursos',
            field=models.ManyToManyField(to='estagio.curso'),
        ),
        migrations.AlterField(
            model_name='estudante_vaga',
            name='TCE',
            field=models.FileField(blank=True, null=True, upload_to='TCE', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Termo de Compromisso de Estágio'),
        ),
    ]
