# Generated by Django 4.2.2 on 2023-09-06 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estagio', '0032_locais_de_estagio_cursos_alter_estudante_vaga_tce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudante_vaga',
            name='vaga',
        ),
    ]
