# Generated by Django 3.2.15 on 2023-12-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagio', '0034_auto_20231129_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante_vaga',
            name='status',
            field=models.CharField(choices=[('0', 'Candidato'), ('1', 'Estagiando'), ('2', 'Estágio concluído'), ('3', 'Candidatura cancelada')], default=0, max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historico_processo',
            name='status',
            field=models.CharField(choices=[('0', 'Aguardando liberação de vaga'), ('1', 'Lista de espera'), ('2', 'Aguardando reenvio do TCE'), ('3', 'Aguardando termo assinado pelas partes'), ('4', 'Processo de seleção concluída'), ('5', 'Estágio concluído'), ('6', 'Candidatura cancelada')], default=0, max_length=1, verbose_name='Status'),
        ),
    ]
