# Generated by Django 3.2.15 on 2023-12-21 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sala_do_empreendedor', '0016_auto_20231218_1356'),
        ('bemestaranimal', '0004_remove_catalogo_raca_animal_raca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiros_SSUBEA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciente', models.BooleanField(default=False, verbose_name='Declaro que estou ciente e de acordo com os termos de parceria da SSUBEA.')),
                ('dt_register', models.DateField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sala_do_empreendedor.empresa')),
                ('user_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
