# Generated by Django 3.2.15 on 2023-12-22 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sala_do_empreendedor', '0016_auto_20231218_1356'),
        ('bemestaranimal', '0006_auto_20231221_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceiros_ssubea',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sala_do_empreendedor.empresa', verbose_name='Selecione sua empresa em questão de parceria com a SSUBEA'),
        ),
    ]
