# Generated by Django 3.2.17 on 2023-02-22 23:09

import casa_do_trabalhador.validations
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do cargo')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='NOME')),
                ('cnpj', models.CharField(max_length=14, unique=True, validators=[casa_do_trabalhador.validations.validate_CNPJ], verbose_name='CNPJ')),
                ('endereco', models.CharField(blank=True, max_length=60, verbose_name='Endereço p/ encaminhamento')),
                ('bairro', models.CharField(blank=True, default='', max_length=60, verbose_name='Bairro')),
                ('telefone', models.CharField(blank=True, max_length=11, validators=[casa_do_trabalhador.validations.validate_TELEFONE], verbose_name='Telefone p/ encaminhamento')),
                ('whatsapp', models.CharField(blank=True, max_length=11, validators=[casa_do_trabalhador.validations.validate_TELEFONE], verbose_name='Whatsapp p/ encaminhamento')),
                ('email', models.CharField(blank=True, max_length=254, verbose_name='Email p/ encaminhamento')),
                ('ocultar', models.BooleanField(choices=[(True, 'Ocultar informações da empresa ao encaminhar'), (False, 'Exibir informações da empresa ao encaminhar')], default=True, verbose_name='Informações da empresa')),
                ('contato_presencial', models.BooleanField(default=False, verbose_name='Contato presencial')),
                ('contato_email', models.BooleanField(default=False, verbose_name='Contato por email')),
                ('contato_telefone', models.BooleanField(default=False, verbose_name='Contato por telefone')),
                ('contato_whatsapp', models.BooleanField(default=False, verbose_name='Contato por whatsapp')),
                ('observacao', models.TextField(blank=True, default='', verbose_name='Observações internas')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Escolaridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome da escolaridade')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga_Emprego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidadeVagas', models.IntegerField(verbose_name='Quantidade de vagas')),
                ('tipo_de_vaga', models.CharField(choices=[('NML', 'Padrão'), ('JAP', 'Jovem aprendiz'), ('PED', 'Pessoa com deficiência'), ('EST', 'Estágio')], default='NML', max_length=3)),
                ('salario', models.CharField(blank=True, default='', max_length=50, verbose_name='Salário')),
                ('carga_horaria', models.CharField(blank=True, default='', max_length=50, verbose_name='Carga Horária')),
                ('regime', models.CharField(blank=True, default='', max_length=100)),
                ('experiencia', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Experiência')),
                ('atribuicoes', models.TextField(blank=True, default='', verbose_name='Atribuições')),
                ('destaque', models.BooleanField(default=False)),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão')),
                ('dt_desativacao', models.DateTimeField(blank=True, null=True, verbose_name='Dt. Desativação')),
                ('ativo', models.BooleanField(default=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casa_do_trabalhador.cargo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casa_do_trabalhador.empresa')),
                ('escolaridade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casa_do_trabalhador.escolaridade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vaga de Emprego',
                'verbose_name_plural': 'Vagas de Emprego',
                'ordering': ['cargo', 'empresa'],
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do candidato')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF do candidato')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento do candidato')),
                ('sexo', models.CharField(choices=[('m', 'Masculino'), ('f', 'Feminino'), ('o', 'Outro')], max_length=1, verbose_name='Sexo do candidato')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email p/ contato com o candidato')),
                ('celular', models.CharField(max_length=15, validators=[casa_do_trabalhador.validations.validate_TELEFONE], verbose_name='Celular p/ contato com o candidato')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro do candidato')),
                ('candidato_online', models.BooleanField(default=False, verbose_name='Candidato online')),
                ('candidato_ativo', models.BooleanField(default=True)),
                ('conseguiu_vaga', models.BooleanField(default=False)),
                ('dt_aquisicao', models.CharField(default='', max_length=10)),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Data de inclusão do candidato')),
                ('dt_atualizacao', models.DateTimeField(blank=True, null=True, verbose_name='Data da última atualização do candidato')),
                ('escolaridade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casa_do_trabalhador.escolaridade')),
                ('funcionario_encaminhamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casa_do_trabalhador.vaga_emprego')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'ordering': ['nome'],
            },
        ),
    ]
