# Generated by Django 3.2.15 on 2024-07-01 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas_recadastramento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscricao',
            old_name='numero',
            new_name='numero_inscricao',
        ),
    ]
