# Generated by Django 3.2.15 on 2024-07-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas_recadastramento', '0002_rename_numero_inscricao_numero_inscricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoarecadastramento',
            name='responsavel_tributario',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
