# Generated by Django 3.2.15 on 2024-07-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas_recadastramento', '0003_alter_pessoarecadastramento_responsavel_tributario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoarecadastramento',
            name='estado',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
