# Generated by Django 3.2.15 on 2024-07-17 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financas_recadastramento', '0004_alter_pessoarecadastramento_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='pessoa_recadastramento',
        ),
        migrations.AlterField(
            model_name='processo',
            name='requerente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financas_recadastramento.pessoarecadastramento'),
        ),
    ]
