# Generated by Django 3.2.15 on 2024-08-15 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financas_recadastramento', '0006_alter_inscricao_numero_inscricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoarecadastramento',
            name='user_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
