# Generated by Django 3.2.15 on 2024-08-15 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financas_recadastramento', '0007_pessoarecadastramento_user_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='cadastro_interno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='user_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pessoarecadastramento',
            name='cadastro_interno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='processo',
            name='user_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
