# Generated by Django 3.2.15 on 2024-08-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas_recadastramento', '0008_auto_20240815_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='numero_inscricao',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
