# Generated by Django 3.2.15 on 2024-10-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas_recadastramento', '0009_alter_inscricao_numero_inscricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoarecadastramento',
            name='cpf_procurador',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pessoarecadastramento',
            name='cpf_responsavel',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pessoarecadastramento',
            name='email_procurador',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pessoarecadastramento',
            name='email_responsavel',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pessoarecadastramento',
            name='nome_procurador',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pessoarecadastramento',
            name='telefone_procurador',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='pessoarecadastramento',
            name='telefone_responsavel',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
