# Generated by Django 4.2.2 on 2024-10-07 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financas_recadastramento', '0010_auto_20241004_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoarecadastramento',
            name='cpf_procurador',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.CreateModel(
            name='Servidor_Recadastramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=False)),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
