# Generated by Django 4.2.2 on 2024-10-07 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0006_consultor_sebrae'),
        ('financas_recadastramento', '0011_alter_pessoarecadastramento_cpf_procurador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor_recadastramento',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacao.pessoa'),
        ),
    ]
