# Generated by Django 3.2.15 on 2024-10-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas_recadastramento', '0012_alter_servidor_recadastramento_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoarecadastramento',
            name='bairro_responsavel',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pessoarecadastramento',
            name='cep_responsavel',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='pessoarecadastramento',
            name='cidade_responsavel',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pessoarecadastramento',
            name='complemento_responsavel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pessoarecadastramento',
            name='estado_responsavel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pessoarecadastramento',
            name='numero_responsavel',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pessoarecadastramento',
            name='rua_responsavel',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
